trigger:
    - qa

variables:
    azureSubscription: ARMSC
    dockerRegistryServiceConnection: DockerSCQA

    resourceGroup: thub-qa
    acrName: thubqa
    containerAppName: thub-app
    imageName: thub-app
    tag: $(Build.BuildId)

pool:
    vmImage: ubuntu-latest

stages:
    - stage: BuildAndDeploy
      jobs:
          - job: Build
            steps:
                - checkout: self

                - task: AzureCLI@2
                  inputs:
                      azureSubscription: $(azureSubscription)
                      scriptType: bash
                      scriptLocation: inlineScript
                      inlineScript: |
                          az account show

                - task: Docker@2
                  inputs:
                      command: buildAndPush
                      repository: $(imageName)
                      dockerfile: Dockerfile
                      containerRegistry: $(dockerRegistryServiceConnection)
                      tags: |
                          $(tag)

                - task: AzureCLI@2
                  inputs:
                      azureSubscription: $(azureSubscription)
                      scriptType: bash
                      scriptLocation: inlineScript
                      inlineScript: |
                          set -e
                          IMAGE="$(acrName).azurecr.io/$(imageName):$(tag)"
                          echo "Deploying image: ${IMAGE}"

                          az containerapp update \
                            --name $(containerAppName) \
                            --resource-group $(resourceGroup) \
                            --image "${IMAGE}"
