steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/thub-gke/thub-app:$SHORT_SHA', '.']
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/thub-gke/thub-app:$SHORT_SHA']
    - name: 'gcr.io/cloud-builders/gke-deploy'
      args:
          - run
          - --filename=k8s/deployment.yaml
          - --image=us-central1-docker.pkg.dev/$PROJECT_ID/thub-gke/thub-app:$SHORT_SHA
          - --location=us-central1
          - --cluster=my-cluster
substitutions:
    _CLUSTER: thub-app
    _REGION: us-central1
