version: '3.1'

services:
  flowise:
    build: .  # Build the image from the current directory
    restart: always
    environment:
      # ... your environment variables
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ~/.flowise:/root/.flowise
    command: /bin/sh -c "sleep 3; pnpm start"
