export const WHITELIST_URLS = [
    '/api/v1/verify/apikey/',
    '/api/v1/chatflows/apikey/',
    '/api/v1/chatflows/',
    '/api/v1/public-chatflows',
    '/api/v1/public-chatbotConfig',
    '/api/v1/public-executions',
    '/api/v1/prediction/',
    '/api/v1/vector/upsert/',
    '/api/v1/node-icon/',
    '/api/v1/components-credentials-icon/',
    '/api/v1/chatflows-streaming',
    '/api/v1/cowork/sessions/',
    '/api/v1/chatflows-uploads',
    '/api/v1/openai-assistants-file/download',
    '/api/v1/feedback',
    '/api/v1/leads',
    '/api/v1/get-upload-file',
    '/api/v1/ip',
    '/api/v1/ping',
    '/api/v1/version',
    '/api/v1/attachments',
    '/api/v1/metrics',
    '/api/v1/nvidia-nim',
    '/api/v1/auth/resolve',
    '/api/v1/auth/login',
    '/api/v1/auth/refreshToken',
    '/api/v1/settings',
    '/api/v1/account/logout',
    '/api/v1/account/verify',
    '/api/v1/account/register',
    '/api/v1/account/resend-verification',
    '/api/v1/account/forgot-password',
    '/api/v1/account/reset-password',
    '/api/v1/account/basic-auth',
    '/api/v1/loginmethod',
    '/api/v1/pricing',
    '/api/v1/auth/register',
    '/api/v1/auth/login',
    '/api/v1/auth/google',
    '/api/v1/auth/microsoft',
    '/api/v1/auth/send-otp',
    '/api/v1/auth/verify-otp',
    '/api/v1/auth/check-email',
    '/api/v1/auth/forgot-password',
    '/api/v1/auth/reset-password',
    '/api/v1/auth/invite-user',
    '/api/v1/auth/invite/validate',
    '/api/v1/auth/invite/accept',
    '/api/v1/auth/workspace-users',
    '/api/v1/auth/workspace-user',
    '/api/v1/auth/workspace-user/role',
    '/api/v1/auth/workspace-user/transfer-admin',
    '/api/v1/auth/superadmin/workspaces',
    '/api/v1/auth/superadmin/workspace',
    '/api/v1/auth/userdata',
    '/api/v1/auth/update-user',
    '/api/v1/user/test',
    '/api/v1/oauth2-credential/callback',
    '/api/v1/oauth2-credential/refresh',
    '/api/v1/text-to-speech/generate',
    '/api/v1/text-to-speech/abort',
    '/api/v1/subscription/create',
    '/api/v1/subscription/validate',
    '/api/v1/subscription/activate-free',
    '/api/v1/subscription/enterprise-mail',
    '/api/v1/notifications/otp/send',
    '/api/v1/notifications/otp/verify',
    '/api/v1/notifications/contact',
    // JWT-protected routes — global API-key check skipped, route-level authMiddleware handles auth
    '/api/v1/auth/me',
    '/api/v1/auth/protected',
    '/api/v1/cowork/',
    '/api/v1/apikey/',
    '/api/v1/assistants/',
    '/api/v1/credentials/',
    '/api/v1/datasets/',
    '/api/v1/document-store/',
    '/api/v1/evaluations/',
    '/api/v1/evaluators/',
    '/api/v1/executions/',
    '/api/v1/export-import/',
    '/api/v1/tools/',
    '/api/v1/variables/',
    // Public routes missing from whitelist
    '/api/v1/nodes',
    '/api/v1/components-credentials',
    '/api/v1/marketplaces',
    '/api/v1/stats',
    '/api/v1/validation/',
    '/api/v1/image-upload',
    '/api/v1/users/update'
]

export const enum GeneralErrorMessage {
    UNAUTHORIZED = 'Unauthorized',
    UNHANDLED_EDGE_CASE = 'Unhandled Edge Case',
    INVALID_PASSWORD = 'Invalid Password',
    NOT_ALLOWED_TO_DELETE_OWNER = 'Not Allowed To Delete Owner',
    INTERNAL_SERVER_ERROR = 'Internal Server Error'
}

export const enum GeneralSuccessMessage {
    CREATED = 'Resource Created Successful',
    UPDATED = 'Resource Updated Successful',
    DELETED = 'Resource Deleted Successful',
    FETCHED = 'Resource Fetched Successful',
    LOGGED_IN = 'Login Successful',
    LOGGED_OUT = 'Logout Successful'
}

export const DOCUMENT_STORE_BASE_FOLDER = 'docustore'

export const OMIT_QUEUE_JOB_DATA = [
    'componentNodes',
    'appDataSource',
    'sseStreamer',
    'telemetry',
    'cachePool',
    'usageCacheManager',
    'abortControllerPool'
]

export const INPUT_PARAMS_TYPE = [
    'asyncOptions',
    'asyncMultiOptions',
    'options',
    'multiOptions',
    'array',
    'datagrid',
    'string',
    'number',
    'boolean',
    'password',
    'json',
    'code',
    'date',
    'file',
    'folder',
    'tabs'
]

export const LICENSE_QUOTAS = {
    // Renew per month
    PREDICTIONS_LIMIT: 'quota:predictions',
    // Static
    FLOWS_LIMIT: 'quota:flows',
    USERS_LIMIT: 'quota:users',
    STORAGE_LIMIT: 'quota:storage',
    ADDITIONAL_SEATS_LIMIT: 'quota:additionalSeats'
} as const
