name: Azure Container Apps Deploy

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: 'Login via Service Principal'
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Build and deploy Container App
              uses: azure/container-apps-deploy-action@v1
              with:
                  appSourcePath: ${{ github.workspace }}
                  acrName: ca7a4dd637e6acr
                  containerAppName: thub-app
                  resourceGroup: gs_rg_0361
              env:
                  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
                  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
                  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
                  AZURE_GOOGLE_CLIENT_ID: ${{ secrets.AZURE_GOOGLE_CLIENT_ID }}
                  AZURE_GOOGLE_CLIENT_SECRET: ${{ secrets.AZURE_GOOGLE_CLIENT_SECRET }}
                  AZURE_GITHUB_CLIENT_ID_APP: ${{ secrets.AZURE_GITHUB_CLIENT_ID_APP }}
                  AZURE_GITHUB_CLIENT_SECRET_APP: ${{ secrets.AZURE_GITHUB_CLIENT_SECRET_APP }}
                  AZURE_GITHUB_CLIENT_ID_DEMO: ${{ secrets.AZURE_GITHUB_CLIENT_ID_DEMO }}
                  AZURE_GITHUB_CLIENT_SECRET_DEMO: ${{ secrets.AZURE_GITHUB_CLIENT_SECRET_DEMO }}
                  AZURE_GITHUB_CLIENT_ID_LOCAL: ${{ secrets.AZURE_GITHUB_CLIENT_ID_LOCAL }}
                  AZURE_GITHUB_CLIENT_SECRET_LOCAL: ${{ secrets.AZURE_GITHUB_CLIENT_SECRET_LOCAL }}
                  AZURE_GITHUB_VITE_GOOGLE_CLIENT_ID: ${{ secrets.AZURE_GITHUB_VITE_GOOGLE_CLIENT_ID }}
                  AZURE_VITE_GITHUB_CLIENT_ID: ${{ secrets.AZURE_VITE_GITHUB_CLIENT_ID }}
